---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"] # works when there is mixed Servers
    # when: ansible_distribution == "Ubuntu" # works With Ubuntu Only

  - name: install apache2 package
    apt:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install neofetch
    apt:
      name: neofetch
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]
