---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    package:
      update_cache: yes
    when: ansible_distribution in ["Debian","Ubuntu"] # works when there is mixed Servers
    # when: ansible_distribution == "Ubuntu" # works With Ubuntu Only

  - name: install apache2 package
    package:
      name: apache2
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: add php support for apache2
    package:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install neofetch
    package:
      name: neofetch
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  # 10.6.2024  
  - name: install sudo
    package:
      name: sudo
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install nala
    package:
      name: nala
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install git
    package:
      name: git
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]

  - name: install curl
    package:
      name: curl
      state: latest
    when: ansible_distribution in ["Debian","Ubuntu"]
       
