---

- hosts: all
  become: true
  tasks:

  - name: update repo index
    apt:
      update_cache: yes
 
 # change state to absent
  - name: install apache2 package
    apt:
      name: apache2
      state: latest

  - name: add php support for apache2
    apt:
      name: libapache2-mod-php
      state: latest

  - name: install neofetch
    apt:
      name: neofetch
      state: absent
